# Generated by Django 3.0.6 on 2021-05-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default=1, upload_to='uploads/customerimages/'),
            preserve_default=False,
        ),
    ]
